// Generated by Wrangler by running `wrangler types --env-interface CloudflareWorkerEnvironment`

interface CloudflareWorkerEnvironment {
	KV: KVNamespace;
	APP__ENV: "local" | "development" | "staging" | "production";
	APP__NAME: "Breeze Stack - Local" | "Breeze Stack - Development" | "Breeze Stack - Staging" | "Breeze Stack";
	BETTER_AUTH__SECRET: string;
	DB: D1Database;
	AI: Ai;
}
